title = "Han highemerly"
baseURL = "https://highemerly.net/"
theme = "hugo-resume"
languageCode = "ja"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Chiba, Japan"
email = "highemerly@me.com"
favicon = "/favicon.ico"
firstName = "Han"
lastName = "Highemerly"
phone = ""
profileImage = "img/icon.jpg"
showEducation = false
showExperience = false
showOpenSource = false
showProjects = true
showPublications = true
showQr = false
showSkills = false
showAccounts = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://handon.club/@highemerly/"
name = "Mastodon"

[[params.handles]]
link = "https://keybase.io/highemerly"
name = "Keybase"

[[params.handles]]
link = "https://github.com/highemerly/"
name = "GitHub"


[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
